# Generated by Django 3.0.11 on 2020-11-11 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201111_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='boards',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tasks',
        ),
    ]
