# Generated by Django 3.0.11 on 2020-11-11 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_auto_20201111_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='accomplished_by',
        ),
        migrations.AddField(
            model_name='card',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='attachements',
            field=models.FileField(upload_to='attachements/', verbose_name='attachement File'),
        ),
    ]
