# Generated by Django 3.0.11 on 2020-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201110_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Premium', 'pre'), ('Free', 'free')], default='Free', max_length=30),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
