# Generated by Django 3.0.11 on 2020-11-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201110_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('pre', 'Premium'), ('free', 'Free')], default='Free', max_length=30),
        ),
    ]
